### PR TITLE
Add `Package.swift` for Swift Package Manager support

### PR DESCRIPTION
**Pull request by hisaac**
It would be great if this library had easy SPM support. Being the libraries are already setup as XCFrameworks, it shouldn't be too difficult. I've included an example `Package.swift` file that I believe would do the trick.

The URLs in the file aren't real obviously. The frameworks would have to be re-uploaded — SPM requires that xcframeworks are individually zipped, and exist at the root of the zip file — but hopefully that isn't too much work.

This would go a long way toward making the libraries easier to work with by developers. Please consider!

### CODE REVIEW

**Comment by waterskier2007** [comment]
This would be an excellent add. I'd imagine many consumers are attempting to get off CocoaPods or other package managers.

**Comment by JeremyWright** [comment]
Hey thanks for the feedback. We're looking into updating our automated deployment to allow for this use case for our next release.

**Comment by hisaac** [comment]
Great! Thanks for considering it. :)

**Comment by paulanatoleclaudot-betclic** [comment]
Is there any update on the support of SPM ?

**Comment by mthole** [comment]
+1, I came here looking for exactly this.

**Comment by aeisses** [comment]
> It would be great to see this merged 👍
> 
> Anyone else seeing this error when uploading to App Store Connect?
> 
> ```
> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [<AppName>.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. 
> ```

**Comment by aeisses** [comment]
> > It would be great to see this merged 👍
> > Anyone else seeing this error when uploading to App Store Connect?
> > ```
> > ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [<AppName>.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. 
> > ```

Please see the docs for a solution to the following problem: https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/ios_prepare_for_appstore.htm

**Comment by hisaac** [comment]
I tried signing the CLA, but hit some sort of issue.

When I first tried to sign it, it presented a web page showing just “An error occurred” and an email address to contact (sorry, didn’t get a screenshot of that page).

When I tried to navigate back to the page using the [link](https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fforcedotcom%2FServiceSDK-iOS%2Fpull%2F112) in the original comment in this thread, I see this:
IMG_0010

And when I open the [Details link](https://cla.salesforce.com/status/forcedotcom/ServiceSDK-iOS/pull/112) next to the check above, I see this page:
IMG_0011

Any tips on how to proceed?

**Comment by aeisses** [comment]
Hello @KoCMoHaBTa @hisaac @mikelrob @mthole @paulanatoleclaudot-betclic @waterskier2007 

We have released a Swift Package Manager for the ServiceChat product: https://github.com/Salesforce-Async-Messaging/Swift-Package-ServiceChat. This will be supported going forward.
ServiceKnowledge and ServiceCases are in the End Of Life process at Salesforce and Swift Package Manager will not be released for these product.

Just for reference all future Chat development will be done on the recently released Messaging In App product: https://service-cloud.herokuapp.com/messaging-in-app/overview The Messaging In App product is the next generation Chat product and supports some key feature like push notifications that the existing ServiceChat does not. It is available using Swift Package Manger, CocoaPods and direct frameworks. ServiceChat is being moved into maintenance mode and will only have major bug fixes going forward.

Big thanks to @KoCMoHaBTa for coming up with a method to use Swift Package Manager on the ServiceChat SDK. That implemented has been used in the supported Swift Package Manager release.

The Swift Package Manager that has been released has been tested for App Store upload and works. I am going to close this  PR as it will not be merged into this repo.

Thanks,
Aaron

**Comment by waterskier2007** [comment]
Thank you @aeisses! Is there any plan for ServiceCore and ServiceSOS?

**Comment by KoCMoHaBTa** [comment]
Thanks for the info @aeisses
Currently we are using both ServiceKnowledge and ServiceChat, so i was wondering what is the replacement for ServiceKnowledge? Is that the new Messaging app you mentioned?
Is there any migration guide for moving to it?

In general, even that ServiceKnowledge and ServiceCases are EOL, unless there is a direct replacement, i think it would still worth it to add SPM support for them until a replacement is available.

**Comment by aeisses** [comment]
@KoCMoHaBTa I do not know of a planned replacement for ServiceKnowledge and ServiceCases, we do not have a plan to support them with Swift Package Manager. If you would like these product please enter a feature request through your Salesforce represenative or through the public portal:

**Comment by aeisses** [comment]
@KoCMoHaBTa I do not know of a product to replace ServiceKnowledge or ServiceCase. As of now they will not be supported with Swift Package Manager. Messaging for In-App is only a ServiceChat replacement. If you would like to request these features please reach out to your Salesforce account team representative or add a feature request at the Ideas Exchange: https://ideas.salesforce.com/s/search#t=All&sort=relevancy

As for migration too Messaging for In-App, this is a new product that requires different org permissions. Please reach out to your Salesforce account manage to add the new SKU for Messaging for In-App on your org. It is a $0 SKU.

Thanks,
Aaron

**Comment by skydivedan** [comment]
Is it possible to get the documentation updated as well?

This is the page that describes how to use the SDK:
https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_ios.meta/service_sdk_ios/ios_sdk_install_overview.htm#ios_sdk_install_ios

However, the documentation describes a git URL that doesn't actually exist: ht<span>tps://git</span>hub.com/SalesforceLabs/Swift-ServiceChat

It would be better if that documentation referenced https://github.com/Salesforce-Async-Messaging/Swift-Package-ServiceChat instead. Then at least it would be documented somewhere, instead of inside this closed pull request. It would also be much easier for me to convince other members of my team that this is the supported solution.

**Comment by sfyz** [comment]
@skydivedan Yes, sorry for the delay. We've submitted the documentation changes to our documentation system, but there's a slight delay in getting this content live. It should be live in a week. In the meantime, here is a related page with the correct information: https://github.com/forcedotcom/ServiceSDK-iOS/wiki/Get-the-iOS-SDK

**Comment by KoCMoHaBTa** [comment]
Hey @aeisses Do you know if the [ServiceKnowledge API](https://developer.salesforce.com/docs/atlas.en-us.knowledge_dev.meta/knowledge_dev/resources_knowledge_support.htm) in End of Life process as well? 
We are exploring the possibility to drop the ServiceKnowledge SDK Module from our app and build our own UI, based on that API.

**Comment by JeremyWright** [comment]
Salesforce has multiple GitHub orgs including forcedotcom. We are releasing
the next generation chat solutions on the messaging for async org, and
we’ve decided to bundle the chat product from service sdk on that same org.

**Comment by RamanDaffodil** [comment]
> It would be great to see this merged 👍
> 
> Anyone else seeing this error when uploading to App Store Connect?
> 
> ```
> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [<AppName>.app/Frameworks/ServiceCore.framework/prepare-framework] is not properly signed. 
> ```

I am facing this issue from last one week. Can anyone help me with this?

**Pull request closed without merging**
